name: Publish docker image
on: [push]

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build & Publish
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.6.1
        with:
          push: true
          tags: ghcr.io/nootsponge/haste-server:latest
